<Project>

  <PropertyGroup>
    <RepoDirectory>$(MSBuildThisFileDirectory)</RepoDirectory>
    <RepoKind>GitHub</RepoKind>
    <DefineConstants Condition=" '$(ExtraConstants)' != '' ">$(DefineConstants);$(ExtraConstants)</DefineConstants>
  </PropertyGroup>


  <Import Project="eng\Versions.props"/>
  <Import Project="eng\Packaging.props"/>
  <Import Sdk="PostSharp.Engineering.Sdk" Project="BuildOptions.props"/>
  <Import Sdk="PostSharp.Engineering.Sdk" Project="StrongName.props"/>
  <Import Sdk="PostSharp.Engineering.Sdk" Project="SourceLink.props"/>

  <PropertyGroup>
    <LangVersion>13.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <CompilerVisibleProperty Include="BenchmarkedTypesFractionInverse" />
    <CompilerVisibleProperty Include="BenchmarkedMembersFractionInverse" />
  </ItemGroup>

</Project>