#if !BENCHMARK

using System.Text.RegularExpressions;
using Metalama.Framework.Aspects;
using Metalama.Framework.Code;
using Metalama.Framework.Fabrics;

namespace Metalama.Aspects;

public class MethodFabric : TransitiveProjectFabric
{
    public override void AmendProject(IProjectAmender amender)
    {
        #region fixed and working
        /* Fixed and working tests */

        // FIXED - Error LAMA0611: Error CS8648 in code generated by Metalama: A goto cannot jump to a location after a using declaration.
        // FIXED - Error LAMA0041: 'FabricAspect.OverrideMethod()' threw 'AssertionFailedException' when applied to X
        // FIXED - error CS1061: 'TEntity' does not contain a definition for 'Id' and no accessible extension method 'Id' accepting a first argument of type 'TEntity' could be found (are you missing a using directive or an assembly reference?)
        // FIXED - error CS0452: The type 'TEntity' must be a reference type in order to use it as parameter 'T' in the generic type or method 'DataConnection.GetTable<T>()'
        amender.SelectMany(p => p.Types.SelectMany(t => t.Methods)
                .Where(m => m is { IsAsync: false, IsAbstract: false, IsImplicitlyDeclared: false })
                .Where(m => !m.Attributes.Any(typeof(GeneratedRegexAttribute))))
            .AddAspects(new ForcedJumpOverrideAspect(), new UninlineableOverrideAspect());

        amender.SelectMany(p => p.Types.SelectMany(t => t.Methods)
                .Where(m => m is { IsAsync: true, IsGeneric: false })
                .Where(m => !m.Attributes.Any(typeof(GeneratedRegexAttribute))))
            .AddAspects(new ForcedJumpOverrideAspect(), new UninlineableOverrideAspect());

        // FIXED - error LAMA0611: Error CS0140 in code generated by Metalama: The label '__aspect_return_1' is a duplicate
        amender
            .SelectMany(p => p.Types.SelectMany(t => t.Methods).Where(m => 
                m is { IsAbstract: false, IsImplicitlyDeclared: false }
                && m.GetIteratorInfo() is { IsIteratorMethod: false, EnumerableKind: not EnumerableKind.IAsyncEnumerable and not EnumerableKind.IAsyncEnumerator }))
            .AddAspect<LoggingAspect>();

        // Contracts.
        amender
            .SelectMany(p => 
                p.Types
                    .SelectMany(t => t.Methods)
                    .Where(m => !m.IsImplicitlyDeclared)
                    .Where(m => m is not { IsPartial: true, HasImplementation: false })
                    .Where(m => m.ReturnType != TypeFactory.GetType(SpecialType.Void) && m.GetAsyncInfo().ResultType != TypeFactory.GetType(SpecialType.Void))
                    .Where(m => m.GetIteratorInfo() is not { IsIteratorMethod: true, EnumerableKind: EnumerableKind.IAsyncEnumerable })
                    .Select(m => m.ReturnParameter)
                    .Where(m => !m.Attributes.Any(typeof(GeneratedRegexAttribute))))
            .AddAspectIfEligible<ParameterContract>();

        amender
            .SelectMany(p => 
                p.Types
                    .SelectMany(t =>
                        t.Methods
                            .Where(m => m is not { IsPartial: true, HasImplementation: false })
                            .Where(m => !m.IsImplicitlyDeclared)
                            .Where(m => !m.Attributes.Any(typeof(GeneratedRegexAttribute))))
                    .SelectMany(m => m.Parameters))
            .AddAspectIfEligible<ParameterContract>();
               
        #endregion

        #region errors
        /* Tests causing errors */

        // Using LoggingAspect on IAsyncEnumerable/Enumerator methods (bug #31108).
        // amender
        //    .With(p => p.Types.SelectMany(t => t.Methods).Where(m => 
        //         !m.IsAbstract 
        //         && !m.IsImplicitlyDeclared
        //         && m.GetIteratorInfo() is {EnumerableKind: EnumerableKind.IAsyncEnumerable or EnumerableKind.IAsyncEnumerator} 
        //         && !m.GetAsyncInfo().IsAwaitable))
        //    .AddAspect<LoggingAspect>();

        #endregion
    }
}

#endif