<Project>
  <PropertyGroup>
    <MetalamaVersion Condition="'$(MetalamaVersion)' == ''">2026.1.19</MetalamaVersion>
    <MetalamaCompilerVersion Condition="'$(MetalamaCompilerVersion)' == ''">2026.1.11</MetalamaCompilerVersion>
    <MetalamaTestsNopCommerceReleaseVersion>4.5.47</MetalamaTestsNopCommerceReleaseVersion>
    <MetalamaTestsNopCommerceReleaseMainVersion>4.5.47</MetalamaTestsNopCommerceReleaseMainVersion>
  </PropertyGroup>
</Project>