
<Project>

    <PropertyGroup>
        <MetalamaVersion>2025.1.17</MetalamaVersion>
        <MetalamaBackstageVersion></MetalamaBackstageVersion>
        <MetalamaCompilerVersion>2025.1.11</MetalamaCompilerVersion>
        <MetalamaFrameworkRunTimeVersion></MetalamaFrameworkRunTimeVersion>
    <MetalamaTestsNopCommerceReleaseVersion>4.5.0</MetalamaTestsNopCommerceReleaseVersion><MetalamaTestsNopCommerceReleaseMainVersion>4.5.0</MetalamaTestsNopCommerceReleaseMainVersion></PropertyGroup>

</Project>