
<Project>

    <PropertyGroup>
        <MetalamaVersion>2026.0.8-rc</MetalamaVersion>
        <MetalamaBackstageVersion></MetalamaBackstageVersion>
        <MetalamaCompilerVersion>2026.0.6-rc</MetalamaCompilerVersion>
        <MetalamaFrameworkRunTimeVersion></MetalamaFrameworkRunTimeVersion>
    <MetalamaTestsNopCommerceReleaseVersion>4.5.8-rc</MetalamaTestsNopCommerceReleaseVersion><MetalamaTestsNopCommerceReleaseMainVersion>4.5.8</MetalamaTestsNopCommerceReleaseMainVersion></PropertyGroup>

</Project>